// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Movie struct {
	ID            int64          `json:"id"`
	TmdbID        int32          `json:"tmdb_id"`
	CreatedAt     time.Time      `json:"created_at"`
	LastFetchedAt time.Time      `json:"last_fetched_at"`
	Title         string         `json:"title"`
	ReleaseDate   string         `json:"release_date"`
	PosterUrl     string         `json:"poster_url"`
	Overview      string         `json:"overview"`
	Genres        []string       `json:"genres"`
	VoteAverage   pgtype.Numeric `json:"vote_average"`
	Runtime       int32          `json:"runtime"`
	Version       int32          `json:"version"`
}

type MoviesWatchlist struct {
	ID        int64     `json:"id"`
	UserID    int32     `json:"user_id"`
	MovieID   int32     `json:"movie_id"`
	AddedAt   time.Time `json:"added_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Watched   bool      `json:"watched"`
}

type Token struct {
	Hash   []byte    `json:"hash"`
	UserID int64     `json:"user_id"`
	Expiry time.Time `json:"expiry"`
}

type User struct {
	ID           int64     `json:"id"`
	CreatedAt    time.Time `json:"created_at"`
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	PasswordHash []byte    `json:"password_hash"`
	Version      int32     `json:"version"`
}
